# Generated by Django 4.2.14 on 2024-07-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='reservas.medico'),
            preserve_default=False,
        ),
    ]
