# Generated by Django 4.2.14 on 2024-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cita_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
